version: "2.0"

services:
  redis:
    image: redis:latest
    expose:
      - port: 6379        
        to:
          - service: cosmosrpc
  cosmosrpc:
    image: reecepbcups/better-cosmos-rpcs:1.0.2
    env:
      - API_PORT=4000
      - REDIS_CONN_STRING=redis://redis:6379/0
      - RPC_URL=https://craft-rpc.crafteconomy.io
    depends_on:
      - redis
    expose:
      - port: 4000
        as: 80
        to:
          - global: true 

profiles:
  compute:
    cosmosrpc:
      resources:
        cpu:
          units: 0.25
        memory:
          size: 1Gi
        storage:
          size: 2Gi
    redis:
      resources:
        cpu:
          units: 0.25
        memory:
          size: 1Gi
        storage:
          size: 2Gi
  placement:
    dcloud:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
      pricing:
        cosmosrpc:
          denom: uakt
          amount: 50
        redis:
          denom: uakt
          amount: 50

deployment:
  cosmosrpc:
    dcloud:
      profile: cosmosrpc
      count: 1
  redis:
    dcloud:
      profile: redis
      count: 1